apiVersion: v1alpha
metadata:
  name: Feature XYZ
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./
suites:
  - name: "saucy test"
    match: "cypress/.*.(spec|test).js$"
image:
  base: saucelabs/stt-cypress-mocha-node
  version: latest
sauce:
  region: us-west-1
